[ru]
languageName = "Русский"
weight = 1
title = "Тармолов про работу"

[ru.params]
displayName = "RU"
isoCode = "ru"
description = "Тармолов про работу — про Яндекс, геосервисы, разработку и руководство"
