colorScheme = "slate"
defaultSocialImage = "https://tarmolov.ru/og-image.jpg"
enableSearch = true
defaultAppearance = "dark"
autoSwitchAppearance = true
smartTOC = true
smartTOCHideUnfocusedChildren = true

[header]
  layout = "fixed-fill-blur"

[footer]
  showThemeAttribution = false

[homepage]
  layout = "profile"
  showRecent = true
  recentLimit = 10
  showRecentItems = 10
  showMoreLink = true
  showMoreLinkDest = "/posts/"

[author]
  name = "Тармолов"
  headline = "про работу"
  image = "img/avatar.webp"
  links = [
    { telegram = "https://t.me/tarmolov_work" },
    { github = "https://github.com/tarmolov" },
  ]

[article]
  showDate = true
  showAuthor = false
  showReadingTime = true
  showTableOfContents = true

[list]
  showCards = true
  showSummary = true
  constrainItemsWidth = true
