colorScheme = "slate"
enableSearch = true
defaultAppearance = "dark"
autoSwitchAppearance = true
smartTOC = true
smartTOCHideUnfocusedChildren = true

[header]
  layout = "fixed-fill-blur"

[footer]
  showThemeAttribution = false

[homepage]
  layout = "profile"
  showRecent = true
  recentLimit = 5
  showMoreLink = true
  showMoreLinkDest = "/posts/"

[author]
  name = "Тармолов про работу"
  headline = "Александр Тармолов"
  bio = "Пишу про работу, инструменты и процессы."

[article]
  showDate = true
  showAuthor = false
  showReadingTime = true
  showTableOfContents = true

[list]
  showCards = true
  showSummary = true
  constrainItemsWidth = true
