name: Alexander Tarmolov
description: yet another blog about web development
url: http://tarmolov.ru/
author: Alexander Tarmolov
markdown: redcarpet
pygments: true
permalink: /:categories/:title
exclude: [blocks, Makefile, README.md]
stylus:
  compress: true
  path: ./blocks
